baseURL = 'https://shmartins.netlify.app/'
languageCode = 'pt-pt'
title = 'SH_Martins'
theme = 'paper'
[params]
    dateFormat = "02 Jan 2006"
    github = rmartins-uab'
    name = 'Ricardo Martins'
    bio = 'Student of Computer engineering.'
    avatar = 'shotta.ax@gmail.com' 
disqusShortname = 'shtspk'